### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by gimenete**

### CODE REVIEW

**Comment by EvanHahn** [comment]
I'm building a list of contributors for a new Helmet.js website. Do you have a name and/or website you want me to use to credit you?

**Comment by gimenete** [comment]
@EvanHahn oh, great. Mine was not a great contribution so thanks!

Name: Alberto Gimeno
Website: http://gimenete.net

Thanks!

**Comment by EvanHahn** [comment]
Added you to the list! Stay tuned for the new Helmet website.

**Comment by gimenete** [comment]
Awesome!

**Pull request merged**
